### ISSUE TITLE
Segmentation Error when no upper bound

### ISSUE THREAD

**Issue by jeremyomer** [lab-core/NurseScheduler#1]
When the time limit does not allow for the computation of a feasible solution, the code runs into a segmentation fault. It should be caught. 
For reproduction: 
./bin/staticscheduler --dir datasets/ --instance n030w4 --weeks 6-2-9-1 --his 1 --param paramfiles/default.txt --sol outfiles/default/n030w4_1_6-2-9-1 --timeout 10

**Comment by legraina** [comment]
Close with #27
