### ISSUE TITLE
Stronger formulation of the rotation decomposition

### ISSUE THREAD

**Issue by jeremyomer** [lab-core/NurseScheduler#11]
Try a stronger formulation of the rotation MP where each worked week-end leads to a new level until the maximum number of weekends is worked. At the last level, every rotation where a weekend day is worked is penalized. 
This requires a major revision of the subproblem, since there is one day-shift node per level. Optimality can only be certified by solving one subproblem per level.

**Comment by legraina** [comment]
Close with #27
