### ISSUE TITLE
Allow preferences on shifts and shift types

### ISSUE THREAD

**Issue by jeremyomer** [lab-core/NurseScheduler#7]
Currently, preferences on rest and work periods are specified on specific shifts. Actually, it seems reasonable that these requests could be on all shifts of a given type on a given day (just like they can be on all shifts of a given day). 
Currently, this can be done by enumerating all the shifts of a given type in the preferences, but a more explicit specification would be preferable.

**Comment by legraina** [comment]
Close with #27
